### ISSUE TITLE
au = [0] * (end_frame - start_frame) 在您的代码里面的这行什么意思哦

### ISSUE THREAD

**Issue by dairuining** [jcfszxc/tempfile#3]
if len(audio) < (end_frame - start_frame):
        au = [0] * (end_frame - start_frame)
        for i in range(len(audio)):
            au[i] = audio[i]
        audio = np.array(au)
    return audio

**Comment by jcfszxc** [comment]
判断音频长度是否过短，如果太短就添零至最短长度

**Comment by dairuining** [comment]
您这个代码所有都可以运行吗？  我最近一直在学习您的代码 很感谢

**Comment by jcfszxc** [comment]
加上数据集的完整代码在这里：https://pan.baidu.com/s/1PQsWngE62E5naWMQPTiuUw

哈哈哈 原来上一个问题也是你创建的呀

可以留个联系方式 有不懂的可以问我

**Comment by dairuining** [comment]
谢谢你啊 很感谢你 我的微信  drnajm
